import "./globals.css";

export const metadata = {
  
  title: "CATS Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="overflow-auto md:overflow-hidden h-screen">{children}</div></body>
    </html>
  );
}
